#!/bin/bash

# Before we start, we need to kill the two "profiled" processes that are
# running in this cgroup ONLY.
MYCGROUP=`ps -p $PPID -h -o cgroup`
MYPROFILED=`ps -U $USER -h -o pid,comm,cgroup | grep $MYCGROUP | grep profiled | grep -v grep | awk '{print $1}'`
for PID in $MYPROFILED; do
  COMM=`ps -h -p $PID -o comm`
  if [ $COMM == "profiled" ]; then
    kill $PID
  fi
done
# They will have launched some stuff which hasn't finished yet, so to avoid
# profiling those, wait a moment.
sleep 1

# Now we can go
sps
