#!/bin/bash

BASEDIR=$(dirname $0)

# Terminate our process
$BASEDIR/ckill sps || exit 1

# For regular jobs, the Job ID is sufficient. However, for array jobs,
# we need to reconstruct the special array job ID and set the Job ID
# to that. If we're not in a job, use a default.
JID=${SLURM_JOB_ID}
AID=${SLURM_ARRAY_JOB_ID}
TID=${SLURM_ARRAY_TASK_ID}
if [ ! -z $AID ] && [ ! -z $TID ]; then
  JID=${AID}_${TID}
fi

# Now, need our SPS output directory and root filenames
if [ ! -z $JID ]; then
  SPSDIR=sps-${JID}
else
  SPSDIR=sps-local
fi
SPSROOT=${SPSDIR}/${SPSDIR}

restore_backup () {
  OUT=$1
  BAK="${OUT}.bak"
  # If we got killed in the middle of a rewrite, there may be a backup file
  if [ -f "$BAK" ]; then
    # There might also be a normal file. If so, it's corrupt.
    if [ -f "$OUT" ]; then
      rm -f "$OUT" 
    fi
    # Either way there isn't now, so restore the backup.
    mv "$BAK" "$OUT" 
  fi
}

if [ -d ${SPSDIR} ]; then
    for f in ${SPSROOT}-*.tsv; do
	restore_backup $f &
    done

    wait # For background tasks

  $BASEDIR/sps-pyplot ${SPSDIR} -o ${SPSDIR}/${SPSDIR}.png
fi
