#!/bin/bash

summarise_data () {
  awk 'BEGIN {FS=OFS="\t"} {sum=0; n=0;for(i=3;i<=NF;i++){sum+=$i; ++n}if(NR!=1){print $1,$2,sum}else{print $1,$2,"TOTAL"}}' "$1"
}

for FILE in $@; do
  if [ -f "$FILE" ]; then
    summarise_data "$FILE" &> "$FILE".sum &
  fi
done

wait # For background processes
